DokterPraktekV2/DokterPraktekV2/Controllers/medicinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DokterPraktekV2;
using System.Web.Security;
using DokterPraktekV2.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using DokterPraktekV2.Services;

namespace DokterPraktekV2.Controllers
{
    public class medicinesController : Controller
    { 
        private DokterPraktekEntities db = new DokterPraktekEntities();
        private MedicineAttributeServices MedAttrService = new MedicineAttributeServices();
        
        // GET: medicines
        public ActionResult Index(int? page,string search,string option)
        {
            var idLog = User.Identity.GetUserId();
            var ids = db.doctors.Where(m => m.userId == idLog).First();
            var op = db.Medicines.Where(a => a.DoctorID == ids.userId).ToList();
            var medicine = db.Medicines.Include(m => m.DoctorID);
            var GetDataFromMedicineController = db.AdminMedicineControllers.FirstOrDefault();

            var IsFromCreate = "";
            if (TempData.ContainsKey("IsFromCreate"))
                IsFromCreate = TempData["IsFromCreate"].ToString();
            if(IsFromCreate == "true")
            {
                ViewBag.MessageSuccess = "Input Data Success";
                ViewBag.MessageDisplay = true;
                TempData["IsFromCreate"] = "false";
            }
            else if(IsFromCreate == "failed")
            {
                ViewBag.MessageSuccess = "Cannot Find Existing ID,Please Check Your Input";
                ViewBag.MessageDisplay = true;
                TempData["IsFromCreate"] = "false";
            }
            else
            {
                ViewBag.MessageSuccess = "";
                ViewBag.MessageDisplay = false;
                ViewBag.MsgFrom = false;
            }

            var data = db.Medicines.Select(e => new VM_Stock
            {
                id = e.ID,
                doctorId = e.DoctorID,
                nameMedicine = e.Name,
                BenefitMedicine = e.BenefitMedicine,
                UnitOfMedicine = e.UnitOfMedicine,
                MerkMedicine = e.MerkOfMedicine,
                price = e.Price,
                dateIn = e.DateIn,
                expired = e.ExpireDate,
                inStock = e.Quantity,
                outStock = e.PatientMedicines.Sum(a => a.Quantity),
                remainStock = e.Quantity - e.PatientMedicines.Sum(a => a.Quantity)
            }).ToList().Where(a=>a.doctorId == ids.userId && !string.IsNullOrEmpty(a.MerkMedicine));
            


            if (!String.IsNullOrEmpty(search))
            {
                data = data.Where(s => s.nameMedicine.ToLower().Contains(search.ToLower())).ToList();
            }
            //paged List
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            IPagedList<VM_Stock> listTrans = null;
            
            //make the default of expired date range by 30days
            DateTime estimatedDate = DateTime.Now.Date.AddDays(GetDataFromMedicineController.ExpiredDateRange == 0 ? GetDataFromMedicineController.ExpiredDateRange : 30);

            List<string> listWarna = new List<string>();
            List<string> listStatus = new List<string>();
            foreach (var item in data)
            {
                if(estimatedDate <= item.expired)
                {
                    var warna = "green";
                    var status = !string.IsNullOrEmpty(GetDataFromMedicineController.StatusSecureText) ? GetDataFromMedicineController.StatusSecureText : "SECURE";
                    listWarna.Add(warna);
                    listStatus.Add(status);
                }
                else
                {
                    var warna = "red";
                    var status = !string.IsNullOrEmpty(GetDataFromMedicineController.StatusExpiredText) ? GetDataFromMedicineController.StatusExpiredText : "EXPIRED";
                    listWarna.Add(warna);
                    listStatus.Add(status);
                }
            }
            ViewBag.warna = listWarna;
            ViewBag.status = listStatus;

            listTrans = data.ToPagedList(pageIndex, pageSize);
            return View(listTrans);
        }

        // GET: medicines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // GET: medicines/Create
        public ActionResult Create()
        {
            var GetDataQtyMed = MedAttrService.GetListOfAttribute("Quantity");
            var GetDataQtyMedByUnit = MedAttrService.GetListOfAttribute("Unit");
            List<MedicineAttribute> CheckingID = new List<MedicineAttribute>();

            CheckingID.Add(new MedicineAttribute { AttributeValue = "Existing Product", AttributeName = "CheckID" });
            CheckingID.Add(new MedicineAttribute { AttributeValue = "New Product",AttributeName = "CheckID" });

            ViewBag.QuantityMed = GetDataQtyMed;
            ViewBag.GetDataQtyMedByUnit = GetDataQtyMedByUnit;
            ViewBag.ChekingProduct = CheckingID;
            return View();
        }
        public ActionResult MedicineAdminController()
        {
            var GetData = db.AdminMedicineControllers.FirstOrDefault();
            return View(GetData);
        }
        public ActionResult MedicineConfigurationView()
        {
            ViewBag.MessageSuccess = "";
            ViewBag.MessageDisplay = false;
            ViewBag.AllAttribute = db.MedicineAttributes;

            var IsFromCreate = "";
            if (TempData.ContainsKey("IsInsertDataFromMedConfig"))
                IsFromCreate = TempData["IsInsertDataFromMedConfig"].ToString();
            if (IsFromCreate == "true")
            {
                ViewBag.MessageSuccess = "Input Data Success";
                ViewBag.MessageDisplay = true;
                TempData["IsInsertDataFromMedConfig"] = "false";
            }
            else
            {
                ViewBag.MessageSuccess = "";
                ViewBag.MessageDisplay = false;
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MedicineAdminController(AdminMedicineController adminViewMedicine)
        {
            try
            {
                var GetData = db.AdminMedicineControllers.FirstOrDefault();
                if (GetData == null)
                {
                    db.AdminMedicineControllers.Add(adminViewMedicine);
                }
                else
                {
                    GetData = db.AdminMedicineControllers.FirstOrDefault(e => e.ID == adminViewMedicine.ID);
                    GetData.StatusExpiredText = adminViewMedicine.StatusExpiredText;
                    GetData.StatusSecureText = adminViewMedicine.StatusSecureText;
                    GetData.ExpiredDateRange = adminViewMedicine.ExpiredDateRange;
                }
                ViewBag.MessageSuccess = "Input Data Success";
                ViewBag.MessageDisplay = true;
                db.SaveChanges();
            }
            catch (Exception ex)
            {

            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MedicineConfigurationView(MedicineAttribute medAttr)
        {
            db.MedicineAttributes.Add(medAttr);
            db.SaveChanges();
            TempData["IsInsertDataFromMedConfig"] = "true";
            return RedirectToAction("MedicineConfigurationView");
            //return View();
        }

        public ActionResult DeleteMedConf(int id)
        {
            var GetData = (from item in db.MedicineAttributes
                       where item.ID == id
                       select item
                       ).FirstOrDefault();

            db.MedicineAttributes.Remove(GetData);
            db.SaveChanges();
            return RedirectToAction("MedicineConfigurationView");
        }


        // POST: medicines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        //public ActionResult AdminViewMedicine(AdminViewMedicine adminViewMedicine)
        //{
        //    return View();
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,name,price,quantity,dateIn,ExpireDate,UnitOfMedicine,BenefitMedicine,MerkOfMedicine,QuantityOfMedicine")] Medicine medicine,[Bind(Include ="id,medicineId,statusTransaction,quantity")] MedicineTransaction medtrans,string NewProd)
        {
            var idLog = User.Identity.GetUserId();
            var ids = db.doctors.Where(m => m.userId == idLog).First();
            medicine.DateIn = DateTime.Today;
            ViewBag.getData = db.MedicineTransactions;

            var DataDB = db.Medicines.Where(e => e.DoctorID == ids.userId);
            bool result = false;
            var GetID = 0;
            if (NewProd.Contains("New"))
            {
                result = false;
            }
            else
            {
                foreach (var item in DataDB)
                {
                    if (item.ID == medicine.ID)
                    {
                        result = true;
                        break;
                    }
                }
            }
            

            if (ModelState.IsValid)
            {
                if (result)
                {

DokterPraktekV2/DokterPraktekV2/Views/medicines/Create.cshtml
@model DokterPraktekV2.Medicine

@{
    ViewBag.Title = "Create";
}

<section class="content-header">
    <h1>Input Data for Medicine</h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- /.row -->
    <div class="box box-danger">
        <div class="box-header">
        
        </div>
        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.Label("Select Status of Medicine", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10 form-inline ">
                            @Html.DropDownList("NewProd", new SelectList(ViewBag.ChekingProduct, "AttributeValue", "AttributeValue", "Existing Product"), "", new { @class = "form-control", @id = "cmb" })
                            @Html.EditorFor(model => model.ID, new { htmlAttributes = new { @class = "form-control txtbox" }})
                            @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.Label("Name Of Medicine", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Brand Of Medicine", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MerkOfMedicine, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MerkOfMedicine, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Unit Of Medicine", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(e => e.UnitOfMedicine, new SelectList(ViewBag.GetDataQtyMedByUnit, "AttributeValue", "AttributeValue"), "", new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Benefit Of Medicine", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BenefitMedicine, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BenefitMedicine, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Price Of Medicine", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.Label("Qty / Unit", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10 form-inline">
                            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })

                            @Html.DropDownListFor(e=>e.QuantityOfMedicine, new SelectList(ViewBag.QuantityMed, "AttributeValue", "AttributeValue"), "", new { @class = "form-control" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.Label("Expired Date", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input type="date" name="ExpireDate" class="form-control" />
                            @Html.ValidationMessageFor(model => model.ExpireDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
    $(document).ready(function () {
        $("#cmb").on("change", function () {
            if (this.value == "Existing Product") {
                $(".txtbox").show();
            }
            else {
                $(".txtbox").hide();
                $(".txtbox").val(0);
            }
        });
    });
</script>
}

DokterPraktekV2/DokterPraktekV2/Views/medicines/Delete.cshtml
@model DokterPraktekV2.medicine

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>medicine</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.expired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.expired)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doctor.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctor.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DokterPraktekV2/DokterPraktekV2/Views/medicines/Details.cshtml
@model DokterPraktekV2.medicine

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>medicine</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.expired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.expired)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doctor.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctor.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>


<table class="table">
    <tr>
        <th>
            Nama Obat
        </th>
        <th>
            Nama Dokter
        </th>
        <th>
            Tanggal Masuk
        </th>
        <th>
            Stock In
        </th>
        <th>
            Stock Out
        </th>
        <th>
            Stock
        </th>
        <th></th>
    </tr>

    @foreach (var item in @ViewBag.med)
    {
        <tr>
            <td>
                @item.name
            </td>
            <td>
                @ViewBag.nameMed
            </td>
            <td>
               @item.dateIn
            </td>
            <td>
                @item.quantity
            </td>
            <td>
                @foreach (var ab in ViewBag.Data)
                {
                    @ab.outStock
                }
            </td>
            <td>

            </td>

    </tr>
    }
</table>

DokterPraktekV2/DokterPraktekV2/Views/medicines/Edit.cshtml
@model DokterPraktekV2.Medicine

@{
    ViewBag.Title = "Edit";
}

<section class="content-header">
    <h1>Edit Medicine</h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- /.row -->
    <div class="box box-danger">
        <div class="box-header">
        </div>
        <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    @*<div class="form-group">
                            @Html.LabelFor(model => model.doctorId, "doctorId", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("doctorId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.doctorId, "", new { @class = "text-danger" })
                            </div>
                        </div>*@

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        @Html.Label("Name Of Medicine", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.MerkOfMedicine, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        @Html.Label("Brand Of Medicine", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MerkOfMedicine, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MerkOfMedicine, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.UnitOfMedicine, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        @Html.Label("Unit Of Medicine", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.UnitOfMedicine, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UnitOfMedicine, "", new { @class = "text-danger" })*@
                            @Html.DropDownListFor(e => e.UnitOfMedicine, new SelectList(ViewBag.GetDataQtyMedByUnit, "AttributeValue", "AttributeValue"), "", new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.BenefitMedicine, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        @Html.Label("Benefit Of Medicine", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BenefitMedicine, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BenefitMedicine, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        @Html.Label("Price Of Medicine", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        @Html.Label("Qty / Unit", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10 form-inline">
                            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })

                            @Html.DropDownListFor(e => e.QuantityOfMedicine, new SelectList(ViewBag.QuantityMed, "AttributeValue", "AttributeValue"), "", new { @class = "form-control" })
                        </div>
                    </div>

                    @*<div class="form-group">
                            @Html.LabelFor(model => model.dateIn, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.dateIn, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.dateIn, "", new { @class = "text-danger" })
                            </div>
                        </div>*@

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.ExpireDate, htmlAttributes: new { @class = "control-label col-md-2" })*@
                        @Html.Label("Expired Date", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.ExpireDate, new { htmlAttributes = new { @class = "form-control" } })*@
                            <input type="date" name="ExpireDate" class="form-control" />
                            @Html.ValidationMessageFor(model => model.ExpireDate, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }
        </div>
    </div>
</section>

DokterPraktekV2/DokterPraktekV2/Views/medicines/Index.cshtml
@*@model IEnumerable<DokterPraktekV2.medicine>*@
@using PagedList.Mvc
@model  PagedList.IPagedList<DokterPraktekV2.Models.VM_Stock>
@{
    ViewBag.Title = "Obat";
}

<section class="content-header">
    <h1>Doctor's Medicine</h1>
</section>
@if (ViewBag.MessageDisplay == true)
{
    <div class="alert alert-success">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>@ViewBag.MessageSuccess</strong>
    </div>
}
<section class="content">
    <div class="box box-danger">
        <div class="box-header">     
            @Html.ActionLink("Insert Obat", "Create", "medicines", new { @class = "btn btn-primary" })
        </div>
        <div class="box-body">
            <form method="get" action="/medicines">
                @Html.TextBox("search") <input type="submit" name="submit" value="Search" />
                
            </form>
            <br />
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Brand
                        </th>
                        <th>
                            Unit
                        </th>
                        <th>
                            Benefit
                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            Stock In
                        </th>
                        <th>
                            Date In
                        </th>
                        <th>
                            Expired Date
                        </th>
                        <th>
                            Status
                        </th>
                        <th>
                            Remaining Stock
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                @{
                    int i = 0;
                    var a = "";
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.id
                            </td>
                            <td>
                                <font color="@ViewBag.warna[i]">@item.nameMedicine</font>
                            </td>
                            <td>
                                @item.MerkMedicine
                            </td>
                            <td>
                                @item.UnitOfMedicine
                            </td>
                            <td>
                                @item.BenefitMedicine
                            </td>
                            <td>
                                @item.price
                            </td>
                            <td>
                                @item.inStock
                            </td>
                            <td>
                                @item.dateIn.ToString("dd MMMM yyyy")

                            </td>
                            <td>
                                <font color="@ViewBag.warna[i]">@item.expired.ToString("dd MMMM yyyy")</font>
                            </td>
                            <td>
                                <font color="@ViewBag.warna[i]">@ViewBag.status[i]</font>
                            </td>
                            <td>
                                @if (item.remainStock == null)
                                {
                                    @item.inStock
                                }
                                else
                                {
                                    @item.remainStock
                                }
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.id })
                            </td>
                        </tr>
                        i++;
                    }
                }
            </table>
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            of @Model.PageCount   @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        </div>
    </div>
</section>