DokterPraktekV2/DokterPraktekV2/Controllers/SchedulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DokterPraktekV2.Models;
using DokterPraktekV2.Services;
using PagedList;
namespace DokterPraktekV2.Controllers
{

    public class schedulesController : Controller
    {
        private dayInServices DoctorWorkDay = new dayInServices();
        private DokterPraktekEntities db = new DokterPraktekEntities();
        private bookingListServices BookListService = new bookingListServices();
        private PatientServices patientService = new PatientServices();
        private PhotoService photoService = new PhotoService();

        #region Get List Booking
        // GET: Schedules
        [Authorize(Roles = "admin, superuser")]
        public ActionResult Index(string searchString , string currentFilter , int? page)
        {
            var book = BookListService.BookingList();
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            if(!String.IsNullOrEmpty(searchString))
            {
                book = BookListService.SearchBookingList(searchString);
            }
            int pageNumber = (page ?? 1);
            int pageSize = 15;
            ViewBag.TotalBook = book.Count();
            return View(book.ToPagedList(pageNumber, pageSize));
        }
        #endregion

        #region Get Today Booking List
        [Authorize(Roles = "admin, superuser")]
        public ActionResult TodayBook(string searchString, string currentFilter, int? page)
        {
            var book = BookListService.TodayBookingList();
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                book = BookListService.SearchTodayBookingList(searchString);
            }
            ViewBag.TotalBook = book.Count();
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            return View(book.ToPagedList(pageNumber, pageSize));
        }
        #endregion

        #region Select Doctor
        public ActionResult Select()
        {
            VM_schedules schedule = new VM_schedules();
            schedule.doctors = DoctorWorkDay.ListWorkDays(); // panggil service hari kerja dokter
            //schedule = schedule.doctors.Where(e => e.dayIn.Count > 0 && e.doctorSpecialties.Count > 0);
            return View(schedule);
        }
        #endregion

        #region HttpGet Create Booking
        public ActionResult Create(string id)
        {
            VM_schedules schedule = new VM_schedules();
            ViewBag.photo = schedule.photo;
            schedule.doctors = new List<VM_doctorList>()
            {
                new VM_doctorList { doctorId = id.ToString() }
            };
            var blockDate = DateTime.Now.ToString("yyyy-MM-dd");
            ViewBag.doctorId = id;
            ViewBag.blockDate = blockDate;
            return View(schedule);
        }
        #endregion

        #region HttpPost Create Booking
        [HttpPost]
        public ActionResult Create(VM_schedules data)
        {
            
            //var checkUpload = Request.Files.Count;
            if (!ModelState.IsValid)
            {
                return View(data);
            }
            string docId = data.doctors[0].doctorId; // Choosen doctor id
            var checkSchedule = BookListService.CheckSchedule(data.dateSchedule , docId); // Check schedule service
            if (checkSchedule > 0)
            {
                var checkPatient = BookListService.CheckPatient(data.name , data.phone); // check patient service
                if (checkPatient != null) 
                {
                    var getScheduleByToday = db.Schedules.Where(e => e.PatientID == checkPatient.id).ToList();
                    if (CheckPatientScheduleByToday(getScheduleByToday, data.dateSchedule))
                    {
                        TempData["Error"] = "Error";
                        return RedirectToAction("formResult");
                    }
                    else
                    {
                        var dataBooking = BookListService.CreateBooking(checkPatient.id, docId, data.dateSchedule); // Create booking service
                        TempData["id"] = dataBooking;
                        TempData["Error"] = "";
                        return RedirectToAction("formResult");
                    }
                }
                else
                {
                    var type = "";
                    var dataPatient = patientService.CreatePatient(data); // Create patient service
                    if (data.photo != null)
                    {
                        data.photo = data.photo.Replace("data:image/png;base64,", "");
                        string base64 = data.photo.Substring(data.photo.IndexOf(',') + 1);
                        base64 = base64.Trim('\0');

                        byte[] chartData = Convert.FromBase64String(base64);
                        data.photo = data.name.ToString() + ".png";
                        type = "image/png";
                        photoService.UploadPatientPicture(chartData, type, dataPatient.ID);
                        
                        //type = data.photo.ContentType; // Check image type ryan logic
                        //photoService.UploadPatientPicture(data.photo.InputStream, type, dataPatient.id); // Upload patient pictures to database

                    }
                    else if (data.photo == null)
                    {
                        type = data.photos.ContentType; // Check image type ryan logic
                        photoService.UploadPatientPictureFILE(data.photos.InputStream, type, dataPatient.ID); // Upload patient pictures to database

                    }
                    var dataBooking = BookListService.CreateBooking(dataPatient.ID, docId, data.dateSchedule);  // Create booking service
                    TempData["id"] = dataBooking;
                    TempData["Error"] = "";
                    return RedirectToAction("formResult");
                }
            }
            else
            {
                ModelState.AddModelError("dateSchedule", "Doctor is not available on that day");
                var blockDate = DateTime.Now.ToString("yyyy-MM-dd");
                ViewBag.blockDate = blockDate;
                return View(data);
            }
        }

        private void CreateImage(byte[] chartData, string v)
        {
            throw new NotImplementedException();
        }
        #endregion

        #region Cancel Today Status Booking
        public ActionResult CancelToday(int id)
        {
            var bookingInfo = db.Schedules.First(s => s.ID == id);
            bookingInfo.BookingStatus = "Cancelled";
            db.SaveChanges();
            return RedirectToAction("TodayBook");
        }

        #endregion

        #region Cancel Status Booking
        public ActionResult CancelIndex(int id)
        {
            var bookingInfo = db.Schedules.First(s => s.ID == id);
            bookingInfo.BookingStatus = "Cancelled";
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion

        [HttpGet]
        public ActionResult LivePhoto(int id)
        {
            ViewBag.doctorId = id;
            return View();
        }

      
        #region Sign get
        public ActionResult Sign(string id)
        {
            var model = id;
            return View(model);
        }


        #endregion

        #region SignIn HttpGet

        public ActionResult SignIn(string id)
        {
            VM_SignIn sign = new VM_SignIn();
            sign.doctorId = id;
            var blockDate = DateTime.Now.ToString("yyyy-MM-dd");
            ViewBag.blockDate = blockDate;
            return View(sign);
        }

        #endregion

        #region SignIn HttpPost
        [HttpPost]
        public ActionResult SignIn(VM_SignIn sign)
        {
            if (!ModelState.IsValid)
            {
                return View(sign);
            }
            var checkSchedule = BookListService.CheckSchedule(sign.dateSchedule, sign.doctorId.ToString()); // Check schedule service
            if(checkSchedule > 0)
            {
                var checkPatient = BookListService.CheckPatientById(sign.PatientNumber); // check patient service
                if (checkPatient != null)
                {
                    var getScheduleByToday = db.Schedules.Where(e => e.PatientID == checkPatient.id).ToList();
                    if (CheckPatientScheduleByToday(getScheduleByToday,sign.dateSchedule))
                    {
                        ModelState.AddModelError("PatientNumber", "Limit Booking, You Already Booking for That Day!");
                        return View(sign);
                    }
                    else
                    {
                        var dataBooking = BookListService.CreateBooking(sign.PatientNumber, sign.doctorId.ToString(), sign.dateSchedule); // Create booking service
                        TempData["id"] = dataBooking;
                        TempData.Keep();
                        return RedirectToAction("formResult");
                    }
                }
                else
                {
                    ModelState.AddModelError("PatientNumber", "Your Patient Number is wrong");
                    return View(sign);
                }
            }
            else
            {
                ModelState.AddModelError("dateSchedule", "Doctor is not available on that day");

DokterPraktekV2/DokterPraktekV2/Views/Schedules/Create.cshtml
@model DokterPraktekV2.Models.VM_schedules

@{
    ViewBag.Title = "Create";
}

<br />  
<section class="content-header">
    
</section>
<!-- Main content -->
<section class="content">
    <div class="box box-primary">
        <div class="box-header"><h4>Booking Form</h4></div>
        @using (Html.BeginForm("Create", "schedules", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="box-body">
                <div class="row">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(m => m.doctors[0].doctorId)
                    <div class="form-group col-md-12">
                        @Html.Label("Patient Name", htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-12">
                        @Html.Label("Home Address", htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.homeAddress, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.homeAddress, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-12">
                        @Html.Label("Phone Number", htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-12">
                        @Html.Label("Patient Gender", htmlAttributes: new { @class = "control-label" })<br />
                        @Html.RadioButton("gender", true) Male &nbsp;
                        @Html.RadioButton("gender", false) Female
                    </div>

                    @*<div class="form-group col-md-12">
                @Html.Label("Patient Photo", htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.photo, new { type="file"})
                @Html.ValidationMessageFor(model => model.photo, "", new { @class = "text-danger" })
            </div>*@

                    @*<div class="form-group col-md-12">
            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Live Photo</button>
            @Html.Partial("LivePhoto")
            </div>
            //ryan logic photo
                    *@
                    <div class="form-group col-md-12">
                        @Html.Label("Booking Date", htmlAttributes: new { @class = "control-label" })<br />
                        @Html.TextBoxFor(model => model.dateSchedule, htmlAttributes: new { @type = "date", @min = ViewBag.blockDate, htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.dateSchedule, "", new { @class = "text-danger" })
                    </div>
                    <div id="par">
                        @*<input type="button" id="stop" name="stop" value="STOP"/>*@
                        @*--------------------------------*@
                        <input type="hidden" name="photos" id="filephoto">
                        @*---------------------------------*@
                        <video id="player" width="550" height="400" controls autoplay></video>
                        <canvas id="canvas" width=320 height=240></canvas>
                        <hr />
                        <a href="#" id="capture" class="btn btn-primary"><i class="fa fa-camera"></i> CAPTURE</a>
                        <a href="#" class="btn btn-success" id="btn-download" download="bookingphoto.png"><i class="fa fa-cloud-download"></i> DOWNLOAD</a>
                        <input type="hidden" name="photo" id="photos" />
                    </div>
                    @* ---------------------------- *@
                    <script>
                                          const player = document.getElementById('player');
                                          const canvas = document.getElementById('canvas');
                                          const context = canvas.getContext('2d');
                                          const captureButton = document.getElementById('capture');
                                          var localstream;
                                          var button = document.getElementById('btn-download');
                                          button.addEventListener('click', function (e) {
                                              var dataURL = canvas.toDataURL('image/png');
                                              button.href = dataURL;
                                          });

                                          const constraints = {
                                            video: true,
                                          };

                                          var image = document.getElementById('photo');
                                          captureButton.addEventListener('click', () => {
                                              var images = context.drawImage(player, 0, 0, canvas.width, canvas.height);
                                                  var ba = document.getElementById('canvas').toDataURL('image/png');
                                                 document.getElementById('photos').src = ba;
                                                    document.getElementById('photos').value = ba.toString();


                                                  console.log(ba);
                                          });

                                          navigator.mediaDevices.getUserMedia(constraints)
                                            .then((stream) => {
                                                player.srcObject = stream;
                                                localstream = player.srcObject;
                                            });
                    //-------------------------DELETE HIDDEN-------------------------------------------
                                          var getStr = window.location.search.substr(1);
                                          var getArray = getStr.split("&");
                                          var get = {};

                                          for (var i = 0; i < getArray.length; i++) {
                                              var tmpArray = getArray[i].split("=");
                                              get[tmpArray[0]] = tmpArray[1];
                                          }
                                          if (/Android|webOS|iPhone|iPod|BlackBerry|IEMobile/i.test(navigator.userAgent)) {

                                              var hidden = document.createAttribute("hidden");

                                              var par = document.getElementById("par");
                                              var filephoto = document.getElementById('filephoto');
                                              var players = document.getElementById("player");
                                              var capture = document.getElementById("capture");
                                              var btndown = document.getElementById("btn-download");
                                              var can = document.getElementById("canvas");

                                              document.getElementById('filephoto').setAttribute("type", "file");
                                              //document.getElementsByTagName('video')[0].removeAttribute('video');
                                              //document.getElementsByTagName('video')[0].removeAttribute('controls');
                                              par.removeChild(players);
                                              par.removeChild(can);
                                              par.removeChild(capture);
                                              par.removeChild(btndown);
                                          }
                    //--------------------
                    </script>
                </div>

                <div class="panel-footer">
                    <div class="form-group">
                        <div class="col-md-offset-10">
                            <a href="/schedules/Select" class="btn btn-default">Back</a> &nbsp;
                            <input type="submit" value="Submit" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</section>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DokterPraktekV2/DokterPraktekV2/Views/Schedules/Index.cshtml
@model PagedList.IPagedList<DokterPraktekV2.Models.VM_bookList>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Booking List";
}
<section class="content-header">
    <h1>All Booking</h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- /.row -->
    <div class="box box-danger">
        <div class="box-header">
            <h4>
                <span class="btn btn-primary">
                    Patient Booking List <span class="badge badge-warning">@ViewBag.TotalBook</span>
                </span>
            </h4>
        </div>
        <div class="box-body">
            @using (Html.BeginForm("Index", "schedules", FormMethod.Get))
            {
                <p>

                    Find by patient name: <input id="searchString" name="searchString" type="text">
                    <button type="submit" class="btn btn-primary btn-sm">
                        <span class="glyphicon glyphicon-search"></span> Search
                    </button>

                    @*<input type="submit" value="Search" />*@
                </p>
            }
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>
                            Doctor Name
                        </th>
                        <th>
                            No Booking
                        </th>
                        <th>
                            Patient Name
                        </th>
                        <th>
                            Patient ID
                        </th>
                        <th>
                            Appointment Date
                        </th>
                        <th>
                            Booking Status
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.DoctorName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NoBooking)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.PatientName)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.id)
                        </td>
                        <td>
                            @item.BookDate.ToString("dd-MMM-yy")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BookingStatus)
                        </td>
                        <td>
                            @if (item.BookingStatus == "Booking")
                            {
                                @*@Html.ActionLink("Complete", "CheckIndex", new { id = item.id }) <text> | </text>*@
                                @Html.ActionLink("Cancel", "CancelIndex", new { id = item.id })
                            }
                            else if (item.BookingStatus == "Completed")
                            {

                            }
                            else
                            {

                            }
                        </td>
                    </tr>
                }

            </table>
            <br />
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
        </div>
    </div>
</section>

DokterPraktekV2/DokterPraktekV2/Views/Schedules/LivePhoto.cshtml
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Live Photo</h4>
            </div>
            <div class="modal-body">
                <body>

                    <button id="capture" class="btn btn-primary">CAPTURE</button>
                    <video id="player" width="550" height="400" controls autoplay></video>
                    <canvas id="canvas" width=320 height=240></canvas>
                    
                    <a href="#" class="btn btn-success" id="btn-download" download="bookingphoto.png">Download</a>
                    @*<a href="/Schedules/Create/@ViewBag.doctorId" class="btn btn-success">BACK</a>*@


                    <div id="demo"></div>
                    <script>
                                          const player = document.getElementById('player');
                                          const canvas = document.getElementById('canvas');
                                          const context = canvas.getContext('2d');
                                          const captureButton = document.getElementById('capture');

                                          var button = document.getElementById('btn-download');
                                          button.addEventListener('click', function (e) {
                                              var dataURL = canvas.toDataURL('image/png');
                                              button.href = dataURL;
                                          });

                                          const constraints = {
                                            video: true,
                                          };
                                          captureButton.addEventListener('click', () => {
                                            // Draw the video frame to the canvas.
                                              var image = context.drawImage(player, 0, 0, canvas.width, canvas.height);
                                              image.href = context.drawImage(player, 0, 0, canvas.width, canvas.height);

                                          });

                                          navigator.mediaDevices.getUserMedia(constraints)
                                            .then((stream) => {
                                              player.srcObject = stream;
                                            });
                    </script>
                </body>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

DokterPraktekV2/DokterPraktekV2/Views/Schedules/Sign.cshtml
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Clinic RI9</h4>
            </div>
            <div class="modal-body">
                
                <div class="row text-center">
                    <div class="col-md-12">
                            <div class="caption">
                                <h3>Are you new ?</h3>
                                <br />
                                <p>
                                    <a href="" id="newPatient" class="btn btn-primary">Yes, I am new here</a>
                                    <a href="" id="registeredPatient" class="btn btn-default">No, I already have my patient ID</a>
                                </p>
                            </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

DokterPraktekV2/DokterPraktekV2/Views/Schedules/TodayBook.cshtml
@model PagedList.IPagedList<DokterPraktekV2.Models.VM_bookList>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Today Booking List";
}

<section class="content-header">
    <h1>Today Booking List</h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- /.row -->
    <div class="box box-danger">
        <div class="box-header">
            <h4>
                <span class="btn btn-primary">
                    Today's Patient Booking List <span class="badge">@ViewBag.TotalBook</span>
                </span>
            </h4>
        </div>
        <div class="box-body">
           @using (Html.BeginForm("TodayBook", "schedules", FormMethod.Get))
           {
            <p>
                Find by patient name: <input id="searchString" name="searchString" type="text">
                <button type="submit" class="btn btn-primary btn-sm">
                    <span class="glyphicon glyphicon-search"></span> Search
                </button>
            </p>
           }
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>
                        Doctor Name
                    </th>
                    <th>
                        No Booking
                    </th>
                    <th>
                        Patient Name
                    </th>
                    <th>
                        Patient ID
                    </th>
                    <th>
                        Appointment Date
                    </th>
                    <th>
                        Booking Status
                    </th>
                    <th>Action</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DoctorName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NoBooking)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PatientName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.id)
                    </td>
                    <td>
                        @item.BookDate.ToString("dd-MMM-yy")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookingStatus)
                    </td>
                    <td>
                        @if (item.BookingStatus == "Booking")
                {
                            @*@Html.ActionLink("Complete", "CheckToday", new { id = item.id}) <text> | </text>*@
                            @Html.ActionLink("Cancel", "CancelToday", new { id = item.id })
                        }
                        else if (item.BookingStatus == "Completed")
                        {

                        }
                        else
                        {

                        }
                    </td>
                </tr>
            }

        </table>
        <br />
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
        </div>
    </div>
</section>